name: Test type stubs
on: [push, pull_request]

jobs:
  stubtest:
    name: Run stubtest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy types-protobuf

      - name: Run mypy.stubtest
        run: |
          cd python
          python run_stubtest.py
